version: "3"
services:

  web:
    build: .
    restart: unless-stopped
    env_file:
      - ./instance/app.env
#    volumes:
#      - ./instance/folio.sqlite:/app/instance/folio.sqlite # The sqlite3 file used to live
    networks:
      - folio
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./instance/database.env
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - ./instance/db-data:/var/lib/postgresql/data/
    networks:
      - folio

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      network: host
      args:
        - CERTBOT_EMAIL=$CERTBOT_EMAIL # set in ./instance/nginx-certbot.env
        - DOMAIN_LIST=$DOMAIN_LIST # again, set ./instance/nginx-certbot.env
    restart: unless-stopped
    env_file: ./instance/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx/:/etc/nginx/user_conf.d
    depends_on:
      - web


networks:
  folio:
    driver: bridge

volumes:
  letsencrypt: