version: "3"
services:
  
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      network: host
      args:
        - CERTBOT_EMAIL=$CERTBOT_EMAIL # set in ./instance/nginx-certbot.env
        - DOMAIN_LIST=$DOMAIN_LIST # again, set ./instance/nginx-certbot.env
    restart: unless-stopped
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx/:/etc/nginx/user_conf.d
    networks:
      - folio
    depends_on:
      - web