version: "3"
services:

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
#    volumes:
#      - ./instance/folio.sqlite:/app/instance/folio.sqlite # The sqlite3 file used to live
    networks:
      - folio
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - ./instance/db-data:/var/lib/postgresql/data/
    networks:
      - folio

networks:
  folio:
    driver: bridge

volumes:
  letsencrypt: