version: "3"
services:

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./portfolio:/app/portfolio
    networks:
      - folio
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - folio

networks:
  folio:
    driver: bridge

volumes:
  letsencrypt:
  db-data: